#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers
source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/_register.sh"

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
#=================================================
ynh_script_progression "Validating installation parameters..."

# By default, the runner will use docker to run your builds. PR are welcomes to implement more executors
executor="docker"

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
ynh_script_progression "Storing installation settings..."

ynh_app_setting_set --key=executor --value=$executor

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Make sure docker is running before installing gitlab-runner
if ! systemctl is-active --quiet docker; then
    ynh_systemctl --service=docker --action=restart --wait_until="API listen on /run/docker.sock"
fi

tempdir="$(mktemp -d)"
ynh_setup_source --dest_dir=$tempdir
ynh_setup_source --dest_dir=$tempdir --source_id="images"
dpkg -i $tempdir/gitlab-runner-images.deb $tempdir/gitlab-runner.deb
ynh_safe_rm "$tempdir"

#=================================================
# SETUP GITLAB RUNNER
#=================================================
ynh_script_progression "Configuring GitLab Runner..."

register_runner_set "$gitlab_url" "$token" "$docker_image" "${app:-gitlab-runner}"

#=================================================
# STORE THE CONFIG FILE CHECKSUM
#=================================================

# Calculate and store the config file checksum into the app settings
ynh_store_file_checksum "/etc/$app/config.toml"

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression "Integrating service in YunoHost..."

yunohost service add $app

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
