#!/bin/bash

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/_common.sh"
source /usr/share/yunohost/helpers
source "$SCRIPT_DIR/_register.sh"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Reinstalling GitLab Runner..."

tempdir="$(mktemp -d)"
ynh_setup_source --dest_dir=$tempdir
ynh_setup_source --dest_dir=$tempdir --source_id="images"
dpkg -i $tempdir/gitlab-runner-images.deb $tempdir/gitlab-runner.deb
ynh_safe_rm "$tempdir"

#=================================================
# SETUP GITLAB RUNNER
#=================================================
ynh_script_progression "Configuring GitLab Runner..."

register_runner_set "$gitlab_url" "$token" "$docker_image" "${app:-gitlab-runner}"

#=================================================
# STORE THE CONFIG FILE CHECKSUM
#=================================================

# Calculate and store the config file checksum into the app settings
ynh_store_file_checksum "/etc/$app/config.toml"

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression "Integrating service in YunoHost..."

yunohost service add $app

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
